[workspace]
resolver = "2"
members = [
    "useful",
]

[workspace.package]
version = "0.1.0"
authors = ["Techcable <git@techcable.net>"]
edition = "2021"
# 1.56 - 2021 edition
# 1.64 - workspace.package
# 1.68 - sparse index
# 1.71 - syn@3
#
# if changed, keep in sync with CI
rust-version = "1.64"
repository = "https://github.com/Techcable/useful.rs"
license = "MIT OR Apache-2.0"

[workspace.lints.clippy]
## groups ##

cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

# restrictions

alloc_instead_of_core = "deny"
redundant_test_prefix = "warn" # name test_foo is redundant with #[test] attr
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"

# safety

multiple_unsafe_ops_per_block = "deny"
undocumented_unsafe_blocks = "deny"

## aggressively lint casts ##
# in an ideal world, overflowing casts would panic
# linting them (with deny) is the second best option

cast_lossless = "allow" # lossless casts are fine, lints will catch if types change
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_ptr_alignment = "deny"
cast_sign_loss = "deny"
char_lit_as_u8 = "deny"
fn_to_numeric_cast = "deny"
fn_to_numeric_cast_any = "deny"
fn_to_numeric_cast_with_truncation = "deny"
ptr_as_ptr = "allow" # pointer casts are fine as long as they don't violate another rule

# excessively pedantic (even for clippy::pedantic)

if_not_else = "allow"
items_after_statements = "allow"
# too many false positives
missing_panics_doc = "allow"
# We don't put #[must_use] on len
must_use_candidate = "allow"
needless_continue = "allow"
# done intentionally to make sure certian code type checks
no_effect_underscore_binding = "allow"
# these can actually make things clearer
redundant_else = "allow"
return_self_not_must_use = "allow"
too_many_lines = "allow"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"

[workspace.metadata.cargo-reedme]
note = "Do not edit - automatically generated by cargo-reedme"
